create sequence client_seq start with 1 increment by 1;

create table address
(
    id     bigint generated by default as identity,
    street varchar(255),
    primary key (id)
);

create table client
(
    address_id bigint unique,
    id         bigint not null default nextval('client_seq'),
    name       varchar(255),
    primary key (id)
);

create table phone
(
    client_id bigint,
    id        bigint generated by default as identity,
    number    varchar(255),
    primary key (id)
);

alter table if exists client
    add constraint fk_client_address foreign key (address_id) references address;
alter table if exists phone
    add constraint fk_phone_client foreign key (client_id) references client;
